name: Windows-CPU-Inference-vs2022-x64

on:
  workflow_call:
    inputs:
      clone-can-skip:
        type: string
        required: false
        default: "false"
      ref:
        type: string
        required: false
        default: "v3.4.0"
        description: Branch, tag or commit SHA to build, e.g. v3.4.0
  workflow_dispatch:
    inputs:
      ref:
        type: choice
        required: false
        default: "v3.4.0"
        description: PaddlePaddle version tag to build
        options:
          - v3.4.0
          - v3.3.1
          - v3.3.0
          - v3.2.2
          - v3.2.1
          - v3.2.0
          - v3.1.1
          - v3.1.0
          - v3.0.0
          - v2.6.2
          - v2.6.1
          - v2.6.0
          - v2.5.2
          - v2.5.1
          - v2.5.0
          - v2.4.2
          - v2.4.1
          - v2.4.0
          - v2.3.2
          - v2.3.1
          - v2.3.0

permissions: read-all

env:
  PADDLE_VERSION: 0.0.0

defaults:
  run:
    shell: cmd

jobs:
  build-cpu:
    name: Build CPU (VS2022 x64)
    runs-on: windows-2022
    timeout-minutes: 240
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 1

      - name: Install Ninja
        run: pip install ninja==1.11.1.4

      - name: Configure cmake (VS2022 x64)
        run: |
          rem set vs language to english to block showIncludes
          set VSLANG=1033
          rem 'DISTUTILS_USE_SDK' indicates that the user has selected the compiler
          set DISTUTILS_USE_SDK=1
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          set PreferredToolArchitecture=x64
          rem Set the default generator for cmake to Ninja
          setx CMAKE_GENERATOR Ninja
          if not exist build mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release ^
            -DWITH_GPU=OFF -DWITH_PYTHON=OFF -DWITH_TESTING=OFF ^
            -DWITH_DISTRIBUTE=OFF -DWITH_TENSORRT=OFF -DON_INFER=ON ^
            -DWITH_AVX=ON -DWITH_MKL=OFF ^
            -DWITH_POCKETFFT=OFF -DWITH_UNITY_BUILD=ON ^
            -DMSVC_STATIC_CRT=ON

      - name: Build inference lib (VS2022 x64)
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cd build
          ninja inference_lib_dist

      - name: Upload artifact (VS2022 x64)
        uses: actions/upload-artifact@v4
        with:
          name: fluid_inference-vs2022-x64
          path: build\fluid_inference_install_dir\
          retention-days: 1
